config/routes.rb
Tron2d::Application.routes.draw do
  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',     to: 'users#new'
  match '/signin',     to: 'sessions#new'
  match '/signout',    to: 'sessions#destroy', via: :delete

  match '/play', to: 'sessions#play' 

  resources :rooms

  root :to => 'sessions#new'

end

app/models/player_status.rb
class PlayerStatus < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/room.rb
class Room < ActiveRecord::Base
	
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	include BCrypt

	attr_accessible :nickname, :email, :password, :password_confirmation
	attr_accessor :password, :password_confirmation

	EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
	validates :nickname, :presence => true, 
		:uniqueness => true, :length => { :in => 3..20 }
	validates :email, :presence => true,
		:uniqueness => true, :format => EMAIL_REGEX
	validates :password, :confirmation => true #password_confirmation attr
	validates_length_of :password, :in => 6..20, :on => :create

	before_save { |user| user.email = email.downcase }
	before_save { |user| encrypt_password(user.password) }

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def password
    @password ||= BCrypt::Password.new(hashed_password)
  end

	def encrypt_password(new_pass)
		@password = BCrypt::Password.create(new_pass)
		self.hashed_password = @password
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
  	include SessionsHelper
end

app/controllers/rooms_controller.rb
require "json"

class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    r = $redis
    r.select(1)

    keys = r.keys
    @rooms = Array.new(keys.length)
    len = keys.length - 1
    for i in 0..len
      @rooms[i] = JSON.parse(r[keys[i]])
    end

  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    room_id = params[:id]
    db = $redis
    db.select(1)
    room = db.get(room_id)
    if !room.nil?
      @room_ht = JSON.parse(room)
      pl_keys = @room_ht["players"]
      @players = Array.new
      db.select(0)
      pl_keys.each do |pl|
        @players.push(db.get(pl))
      end
    else
      redirect_to rooms_path
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    db = $redis
    db.select(2)
    keys = db.keys
    @maps = Array.new
    len = keys.length - 1
    for i in 0..len
      map_hash = JSON.parse(db[keys[i]])
      @maps.push([map_hash["name"], map_hash["map_id"]])
    end

    #render 'new'
  end

  # GET /rooms/1/edit
  def edit
    render 'show'
  end

  # POST /rooms
  # POST /rooms.json
  def create
    if !params[:description].empty?
      db = $redis
      # Select ROOM table (1)
      db.select(1)
      room_id = db.keys.max
      if room_id.nil?
        room_id = 1
      else
        room_id = room_id.to_i + 1
      end

      room_ht = Hash.new {|h,k| h[k]=[]}
      room_ht["room_id"] = room_id
      room_ht["description"] = params[:description]
      #room_ht["max"] = params[:max]
      room_ht["map_id"] = params[:map_id]
      room_ht["players"] = [current_user.id]
      room_ht["admin_id"] = current_user.id

      db[room_id] = room_ht.to_json

      db.select(0)
      player_ht = JSON.parse(db[current_user.id])
      player_ht["bike_num"] = 0
      player_ht["room_id"] = room_id
      db[current_user.id] = player_ht.to_json

      redirect_to rooms_path
    else
      redirect_to '/rooms/new', :notice => 'Set description!'
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    cur_room_id = params[:id]
    db = $redis

    db.select(1)
    r_ht = JSON.parse(db.get(cur_room_id))
    db.select(0)
    player_ht = JSON.parse(db.get(current_user.id))

    players = r_ht["players"]

    if params[:purpose] == "join"
      #Refresh player
      player_ht["room_id"] = cur_room_id

      bikes = get_players_bikes_nums(players)
      player_ht["bike_num"] = bikes.max + 1
      db.select(0)
      db[current_user.id] = player_ht.to_json

      #Refresh room
      db.select(1)
      r_ht["players"] = players.push(current_user.id)
      db[cur_room_id] = r_ht.to_json
    else
      # Refresh player
      db.select(0)
      player_ht["room_id"] = nil
      player_ht["color"] = "NO color"
      player_ht["bike_num"] = "NO bike"
      db[current_user.id] = player_ht.to_json

      #Refresh room
      db.select(1)
      r_ht["players"].delete(current_user.id)
      db[cur_room_id] = r_ht.to_json
    end


    redirect_to room_path(cur_room_id)
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    # Only admin can delete rooms!
    db = $redis
    db.select(1)
    db.del(params[:id])
    redirect_to rooms_path
  end

# --------------------------------------------------------------------
def get_players_bikes_nums(players_ids)
    db = $redis
    db.select(0)
    bikes = Array.new
    for i in 0..players_ids.length - 1
      cur_player = JSON.parse(db.get(players_ids[i]))
      bikes.push(cur_player["bike_num"])
    end
    return bikes
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if signed_in?
			redirect_to user_path(current_user)
		end
		#new 
	end

	def create
	  user = User.find_by_email(params[:session][:email].downcase)
	  if user && user.password == params[:session][:password]
	    # Sign the user in and redirect to the user's show page.
	    sign_in user
	    redirect_to user
	  else
	    # Create an error message and re-render the signin form.
	    flash[:error] = 'Invalid email or password'
      	redirect_to signin_path
	  end
	end

	def destroy
		cookies.delete(:nickname)

		redirect_to signin_path
	end

	def play
		render 'play'
	end
end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController

  include BCrypt

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    if signed_in?
      redirect_to user_path(current_user)
    else
      @user = User.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    end
  end

  # GET /users/1/edit
  def edit
    #@user = User.find(params[:id])
    redirect_to current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.wins = 0
    @user.battles = 0
    @user.score = 0

    if @user.save
      sign_in(@user)
      redirect_to current_user,
        notice: 'You have been successfully signed up!'
    else
      render action: "new"
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    	case level
    		when :notice then "alert alert-info"
    		when :success then "alert alert-success"
    		when :error then "alert alert-error"
    		when :alert then "alert alert-error"
    	end
  	end
end

app/helpers/rooms_helper.rb
module RoomsHelper
	
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    	cookies[:nickname] = user.nickname
    	self.current_user = user
      db = $redis
      db.select(0)
      player_ht = Hash.new { |hash, key| hash[key] = [] }
      player_ht["id"] = user.id
      player_ht["nickname"] = user.nickname
      player_ht["bike_num"] = -1
      player_ht["room_id"] = -1
      player_ht["score"] = 0
      player_ht["color"] = nil
      player_ht["state"] = "not_ready"
      db.set(user.id, player_ht.to_json)
  	end

  	def sign_out
      cookies.delete(:nickname)
  		@current_user = nil
  	end

  	def current_user
  		@current_user ||= User.find_by_nickname(cookies[:nickname])
  	end

	def current_user=(user)
		@current_user = user
	end


	def signed_in?
		!(self.current_user.nil?)
	end

  def is_admin?(room_ht)
    current_user.id.to_s == room_ht["admin_id"].to_s
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer ">
  <nav class="navbar navbar-fixed-bottom">
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <!--<li><%= link_to "Contact", '#' %></li> -->
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>

  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="/signin">Awesome Tron 2D</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="">Contacts</a></li>
        <li><a href="">About</a></li>
        <li>
        <% if current_user.nil? %>
          <%= link_to "Sign in", {:controller => "sessions", :action => "new"} %>
        <% else %>
          <%= link_to "Sign out", {controller: "sessions", action: "destroy"}, :confirm => "Are you sure?", method: "delete" %> 
        <% end %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>

</header>

app/views/layouts/_messages.html.erb
<div>
	<% flash.each do |name, msg| %>
	  <% if msg.is_a?(String) %>
	    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
	      <!--<a class="close" data-dismiss="alert">&#215;</a> -->
	      <%= content_tag :div, msg, :id => "flash_#{name}" %>
	    </div>
	  <% end %>
	<% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tron</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <script scr="jquery.js">
      $(document).ready(function() {
        $('form').submit(function() {
          $('input[type=submit]', this).attr('disabled', 'disabled');
        });
      });
    </script>
    <%= render 'layouts/header' %>
    <div align='center'>
      <%= render 'layouts/messages' %>
    </div>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html

app/views/rooms/edit.html.erb
<h1>Editing room</h1>


<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Game rooms</h1>

<script type="text/JavaScript">
<!--
  function timedRefresh(timeoutPeriod) {
      setTimeout("location.reload(true);",timeoutPeriod);
  }
//   -->
</script>

<body onload="JavaScript:timedRefresh(5000);">


<p>Select room, <%= current_user.nickname %>, or create new </p>
<%= button_to 'New Room', new_room_path,
  class: "btn btn-default", :method => 'get' %>
<br><br>

<table class="table table-hover table table-condensed">
	<tr>
		<td>ID</td>
		<td>Description</td>
		<td>Playing / Max players</td>
		<td>Map</td>
	</tr>
	<% @rooms.each do |r| %>
		<tr>
			<td><p><%= r["room_id"] %></p></td>
			<td><%= link_to r["description"], room_path(r["room_id"]) %></td>
			<td><%= r["players"].length %> / <%= r["max"] %></td>
			<td><%= r["map_id"] %></td>
		</tr>
	<% end %>
</table>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= link_to 'Back', rooms_path %>

<br><br>
<%= form_tag(:controller => "rooms", :action => "create", :method => "get") do %>
	<p><%= label_tag(:description) %></p>
	<%= text_field_tag(:description) %>
  <br><br>

  <p><%= label_tag(:map) %></p>
  <%= select_tag(:map_id, options_for_select(@maps)) %>

  <br><br>
	<p>
    <%= submit_tag 'Create', :controller => "action", :rooms => "create", :method => "post", class: "btn btn-default" %>
    <br><br>
	</p>
<% end %>


<%= debug params %>

app/views/rooms/show.html.erb
<head>
</head>
<body id='main_body'>
	<h1>Game room # <%= @room_ht["room_id"] %></h1>

	<%= link_to 'Back', rooms_path %><br><br>

	<% if is_admin?(@room_ht) %>
		<p>You're an admin</p>
		<%= link_to 'Destroy', room_path(@room_ht["room_id"]), method: :delete, :confirm => "Are you sure?" %>
		<br><br>
		<%= link_to "PLAY", '/play', class: "btn btn-custom" %>
		<br><br>
	<% else %>
		<% r_id = @room_ht["room_id"] %>
		<%= form_tag( {:controller => :rooms, :action => :update,
			:id => r_id }, {:method => :put} ) do %>
			<% unless @room_ht["players"].include? current_user.id %>
				<%= hidden_field_tag :purpose, "join" %>
        <%= submit_tag 'Join', class: "btn btn-default" %>
        <br><br>
			<% else %>
				<%= hidden_field_tag :purpose, "unjoin" %>
				<%= submit_tag 'Disconnect', class: "btn btn-default" %>
				<br><br>
				<%= link_to "PLAY", '/play', class: "btn btn-default" %>
      <% end %>
      <br><br>
		<% end %>
	<% end %>

	
	<!--<%= @room_ht["players"] %> -->
	<!--<%= @players.to_json %> -->
	<table id="players_table"
	class="table table-striped table-bordered table-condensed">
		<tr>
			<td><p>Player's name</p></td>
			<td>Color</td>
			<td>Status</td>
			<td>Bike's number</td>
		</tr>
		<% @players.each do |pl| %>
			<% unless pl.nil? %>
				<tr>
					<% pl_ht = JSON.parse(pl) %>
					<td><%= pl_ht["nickname"] %></td>
					<td><%= pl_ht["color"] %></td>
					<td><%= pl_ht["state"] %></td>
					<td><%= pl_ht["bike_num"] %></td>
				</tr>
			<% end -%>
		<% end %>
	</table>


<%= debug params %>	
</body>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Players</h1>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Nickname</th>
    <th>Wins</th>
    <th>Battles</th>
    <th>Score</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.nickname, user %></td>
    <td><%= user.wins %></td>
    <td><%= user.battles %></td>
    <td><%= user.score %></td>
  </tr>
<% end %>
</table>

<br/>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class= "Sign_Form" align="center">
<h1>Sign Up</h1>

<div align="left">
	<% if @user.errors.any? %>
		<ul class="Signup_Errors">
			<% for message_error in @user.errors.full_messages %>
				<li><%= message_error %></li>
			<% end %>
		</ul>
	<% end %>
</div>

<%= form_for(@user) do |f| %>
	<p> Nickname </br> <%= f.text_field :nickname%> </p>
	<p> Email </br> <%= f.text_field :email %> </p>
	<p> Password </br>
	 	<%= f.password_field :password %>
	</p>
	<p> Confirm password </br> 
		<%= f.password_field :password_confirmation %>
	</p>
	<%= f.submit "Sign up", class: "btn btn-default btn-lg" %>
<% end %>



</div>
<br>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2> Welcome back, <%= @user.nickname %> </h2>
<br>
<%= link_to 'All players', users_path %> <br>
<br>
You played <%= @user.battles %> games <br>
You won <%= @user.wins %> battles <br>

<br>
<br>
<%= link_to 'Rooms', rooms_path %>